version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Packaging application for deployment..."
      - mv target/*.jar application.jar
      - echo "Files included in the artifact:"
      - ls -l
artifacts:
  files:
    - application.jar
  discard-paths: yes